---
spring:
  profiles: local
  datasource:
    url: jdbc:mysql://localhost:6033/tecobrary_db?serverTimezone=UTC&useSSL=false
    username: tecobrary
    password: tecobrary
  jpa:
    database-platform: org.hibernate.dialect.MySQL57InnoDBDialect
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
