server:
  port: 9090

logging:
  level:
    root: DEBUG

cors:
  allowed:
    origins:
      - "http://localhost:3000"
    headers:
      - "*"
    methods:
      - "*"
  register-url-pattern: "/**"

spring:
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: * # add
            clientSecret: * # add
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - read:user
              - user:email