version: '3'
services:
  tecobrary-mysql:
    image: mysql:5.7
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=tecobrary_db
      - MYSQL_USER=tecobrary
      - MYSQL_PASSWORD=tecobrary
    ports:
      - "6033:3306"
    volumes:
      - "./mysql/init/batch-meta.sql:/docker-entrypoint-initdb.d/1.sql"